### ISSUE TITLE
imucam-1.bag

### ISSUE THREAD

**Issue by mabeibei0404** [chutsu/yac#1]
Can you provide the  imucam-1.bag's downloading  link?Thanks

**Comment by chutsu** [comment]
Sorry I don't have it anymore, however `yac` has been developed against EuRoC dataset so you can use that instead.

**Comment by chutsu** [comment]
Checkout the usage here: https://github.com/chutsu/yac/blob/master/yac/tests/test_calib_vi.cpp#L151
